### ISSUE TITLE
crash on start download

### ISSUE THREAD

**Issue by DJaeger** [PaperAirplane-Dev-Team/GigaGet#15]
I can not start any download, as the app crashes every time.
I get the new mission dialog, but if I fill it and click okay the dialog closes it adds the download to list and directly crashes before doing anything else.
After restart the app the download list is empty again.

```
I/PackageManager(  751): Adding preferred activity ComponentInfo{us.shandian.giga/us.shandian.giga.ui.main.MainActivity} for user 0 :
I/Timeline(13751): Timeline: Activity_launch_request id:us.shandian.giga time:81323651
I/ActivityManager(  751): START u0 {act=android.intent.action.VIEW dat=https://github.com/mailvelope/mailvelope/releases/download/v0.13.1/mailvelope.firefox.xpi typ=application/x-xpinstall flg=0x7000000 cmp=us.shandian.giga/.ui.main.MainActivity} from pid 13751
I/ActivityManager(  751): Start proc us.shandian.giga for activity us.shandian.giga/.ui.main.MainActivity: pid=13803 uid=10534 gids={50534, 3003, 1028, 1015}
D/ActivityThread(13803): handleBindApplication:us.shandian.giga
I/dalvikvm(13803): Could not find method android.view.View.setElevation, referenced from method us.shandian.giga.ui.main.MainActivity.onCreate
I/ActivityManager(  751): Displayed us.shandian.giga/.ui.main.MainActivity: +944ms
I/Timeline(  751): Timeline: Activity_windows_visible id: ActivityRecord{422d4d60 u0 us.shandian.giga/.ui.main.MainActivity t143} time:81324756
E/AndroidRuntime(13803): Process: us.shandian.giga, PID: 13803
E/AndroidRuntime(13803):    at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:193)
E/AndroidRuntime(13803):    at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:185)
W/ActivityManager(  751):   Force finishing activity us.shandian.giga/.ui.main.MainActivity
E/ActivityThread(13803): Activity us.shandian.giga.ui.main.MainActivity has leaked ServiceConnection us.shandian.giga.ui.main.MainActivity$1@41df6248 that was originally bound here
E/ActivityThread(13803): android.app.ServiceConnectionLeaked: Activity us.shandian.giga.ui.main.MainActivity has leaked ServiceConnection us.shandian.giga.ui.main.MainActivity$1@41df6248 that was originally bound here
E/ActivityThread(13803):    at us.shandian.giga.ui.main.MainActivity.onCreate(MainActivity.java:98)
E/ActivityThread(13803): Activity us.shandian.giga.ui.main.MainActivity has leaked ServiceConnection us.shandian.giga.ui.fragment.MissionsFragment$1@421c99e0 that was originally bound here
E/ActivityThread(13803): android.app.ServiceConnectionLeaked: Activity us.shandian.giga.ui.main.MainActivity has leaked ServiceConnection us.shandian.giga.ui.fragment.MissionsFragment$1@421c99e0 that was originally bound here
E/ActivityThread(13803):    at us.shandian.giga.ui.fragment.MissionsFragment.onCreateView(MissionsFragment.java:74)
I/ActivityManager(  751): Process us.shandian.giga (pid 13803) has died.
W/ActivityManager(  751): Scheduling restart of crashed service us.shandian.giga/.service.DownloadManagerService in 1000ms
```

**Comment by PeterCxy** [comment]
Sorry but this error message is only ActivityManager's and cannot help address the problem. I wonder if you are using some kind of Android 4.4 with no external sdcards?
